### ISSUE TITLE
How would you feel about putting liburing4cpp in a namespace and putting the files in a folder?

### ISSUE THREAD

**Issue by codeinred** [CarterLi/liburing4cpp#20]
One thing I've been thinking about to improve the organization of the project is to give liburing4cpp a namespace and it's own folder. We could move `incude/*` to `include/liburing` or to `include/u_ring` or to `include/uio`, or to another folder, so that people using the library can do:
```cpp
#include <liburing/io_service.hpp>
```
Honestly I'm happy with whatever name you'd like for the folder. We could also put classes inside a namespace, so that they're not in the global namespace. I'm thinking `uio` for this, so it'd be `uio::io_service`, `uio::task`, `uio::resolver`, etc. Here, `uio` would stand for U-ring Input Output. Please give me your feedback, and I'd be happy to create a PR with the changes!

(I wanted to ask about this first b/c it's kind of a major refactor)

**Comment by CarterLi** [comment]
Since this repo is called liburing4cpp, I'd like to keep the name `liburing` if it doesn't conflict with the original `liburing` library. Otherwise `uio` is ok for me.

**Comment by codeinred** [comment]
Since our header files end in .hpp, there shouldn't be any conflict with the liburing library. All of their headers end in .h. Would you be happy with using `liburing/*.hpp` for the headers, and `uio` for the namespace? Or would you prefer `liburing` for both the folder and the namespace? I personally prefer shorter namespace names, but it's up to you!

**Comment by CarterLi** [comment]
I indeed prefer `io_uring` to matches the prefix of all liburing apis

**Comment by codeinred** [comment]
We can do that! It'll be a namespace and name mangling for namespaces is handled in a way that io_uring::my_name is different than io_uring_my_name, so it won't conflict!

**Comment by CarterLi** [comment]
The problems come from `struct io_uring`

**Comment by codeinred** [comment]
I just noticed that when my IDE complained when I tried to add a namespace `io_uring`. Okay. Back to the drawing board. Do you prefer `namespace liburing`, `namespace uio`, or something else?

**Comment by CarterLi** [comment]
Could you please try replacing all `io_uring` type specifer in this repo to `struct io_uring`?

**Comment by codeinred** [comment]
I tried that, but the compiler complains about "redefinition of 'io_uring' as different kind of symbol". It references the previous definition inside `liburing.h`, which we can't change.

**Comment by CarterLi** [comment]
Let's use uio instead

**Comment by codeinred** [comment]
I created a pull request with the changes! If you're happy with it, we can close out this issue!
