### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by gwnet** [CarterLi/liburing4cpp#7]
wayne@wayne-Virtual-Machine:~/liburing4cpp/demo$ make
clang++ ./file_server.cpp ./mime_dicts.cpp -o file_server -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
In file included from ./file_server.cpp:14:
../io_service.hpp:122:42: error: use of undeclared identifier 'io_uring_free_probe'; did you mean 'io_uring_probe'?
        on_scope_exit free_probe([=]() { io_uring_free_probe(probe); });
                                         ^
/usr/include/liburing/io_uring.h:289:8: note: 'io_uring_probe' declared here
struct io_uring_probe {
       ^
In file included from ./file_server.cpp:14:
../io_service.hpp:159:24: error: use of undeclared identifier 'IORING_OP_SHUTDOWN'
        TEST_IORING_OP(IORING_OP_SHUTDOWN);
                       ^
../io_service.hpp:171:29: error: use of undeclared identifier 'IORING_FEAT_SQPOLL_NONFIXED'
        TEST_IORING_FEATURE(IORING_FEAT_SQPOLL_NONFIXED);
                            ^
../io_service.hpp:579:9: error: use of undeclared identifier 'io_uring_prep_tee'
        io_uring_prep_tee(sqe, fd_in, fd_out, nbytes, flags);
        ^
4 errors generated.
make: *** [Makefile:29: file_server] Error 1

**Comment by CarterLi** [comment]
Your `liburing` may be out of date. Don't use the releases, use git HEAD instead.

**Comment by gwnet** [comment]
thank you so much. I already git pull on liburing master. make and install it. then make your code. this is new error:
wayne@wayne-Virtual-Machine:~/liburing4cpp/demo$ make
clang++ ./file_server.cpp ./mime_dicts.cpp -o file_server -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./http_client.cpp -o http_client -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./link_cp.cpp -o link_cp -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./threading.cpp -o threading -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./test.cpp -o test -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./bench.cpp -o bench -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./echo_server.cpp -o echo_server -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
./echo_server.cpp:57:9: error: This won't work because short read of IORING_OP_RECV is not considered an error
#       error This won't work because short read of IORING_OP_RECV is not considered an error
        ^
1 error generated.
make: *** [Makefile:47: echo_server] Error 1

**Comment by CarterLi** [comment]
Why are there so many errors😨

**Comment by CarterLi** [comment]
My fault

[Fixed](https://github.com/CarterLi/liburing4cpp/commit/1e2be4deaba366da45e55248ff440f8daf2ff1d3), sorry for having a bad time :(

**Comment by gwnet** [comment]
yes, it works now. :)

I will find time to play with it. do you know if there is good RPC based lib io uring?

wayne@wayne-Virtual-Machine:~/liburing4cpp/demo$ make 
clang++ ./file_server.cpp ./mime_dicts.cpp -o file_server -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./http_client.cpp -o http_client -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./link_cp.cpp -o link_cp -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./threading.cpp -o threading -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./test.cpp -o test -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./bench.cpp -o bench -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
clang++ ./echo_server.cpp -o echo_server -O0 -rdynamic -D_LIBCPP_DEBUG_LEVEL=1 -fno-omit-frame-pointer -fsanitize=address -fcoroutines-ts -stdlib=libc++ -lc++ -lc++abi -g -Wall -std=c++17 -I.. -I../fmt/include ../fmt/src/format.cc -luring -pthread
wayne@wayne-Virtual-Machine:~/liburing4cpp/demo$ ls
bench        echo_server.cpp  http_client      link_cp.cpp     mime_dicts.hpp  threading
bench.cpp    file_server      http_client.cpp  Makefile        test            threading.cpp
echo_server  file_server.cpp  link_cp          mime_dicts.cpp  test.cpp
wayne@wayne-Virtual-Machine:~/liburing4cpp/demo$

**Comment by codeinred** [comment]
Should we close this one since it seems to be fixed?
